name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    env:
      IMAGE_NAME: lesson-087
      PROJECT_ID: express-backend-411116
      GAR_REPO_NAME: container-images  
    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test  

    - name: Authenticate to Google Cloud
      id: auth
      uses: 'google-github-actions/auth@v1'
      with:
        token_format: access_token
        service_account: 'pipline-service-account@express-backend-411116.iam.gserviceaccount.com'
        workload_identity_provider: 'projects/505110449924/locations/global/workloadIdentityPools/my-workload-identity-pool/providers/my-repo'
        access_token_lifetime: 300s

    - name: Login to Artifact Registry
      uses: docker/login-action@v3
      with:
        registry: us-central1-docker.pkg.dev
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}    
     
    - id: docker-push-tagged
      name: Tag Docker image and push to Google Artifact Registry
      env:
        GIT_TAG: "1.0.1"
      uses: docker/build-push-action@v5
      with:
        push: true
        file: Dockerfile.prod
        tags: |
             us-central1-docker.pkg.dev/express-backend-411116/container-images/express-backend:${{ env.GIT_TAG }}
             us-central1-docker.pkg.dev/express-backend-411116/container-images/express-backend:latest

      

